Первое задание завершено
acceptTheVoid/task_app pull request #1
Opened 2022-10-16 10:08 UTC by acceptTheVoid

2022-10-16 11:57 UTC, 8symbols requested changes
1. Укажите в ридми длину строки, на которую рассчитан форматтер.
2. Почистите `pubspec` от комментариев.
3. Дисмисса вправо быть не должно.
4. Фон у дисмисса должен повторять форму карточки задачи. У вас он больше.
5. Картинка пустого списка задач отсутствует.
6. В диалоге создания задачи после ввода 40 символов дальнейший ввод игнорируется.
7. Тексты ошибок не соответствуют заданию.

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/app_bar_notifier.dart
> +  bool _isOnlyFav = false;
```suggestion
  bool _isOnlyFavorite = false;
```

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/app_bar_notifier.dart
> +  void setUnchecked() {
```suggestion
  void toggleUnchecked() {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/app_bar_notifier.dart
> +  void setOnlyFav() {
```suggestion
  void toggleOnlyFavorite() {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/notifier_controller.dart
> +class NotifierController extends StatefulWidget {
Это скорее провайдер, чем контроллер

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/notifier_controller.dart
> +  late TaskNotifier taskNotifier = TaskNotifier();
У `ChangeNotifier`'ов нужно освобождать ресурсы после использования (`.dispose()`). Сделайте это в методе `dispose` стейта, а сами нотифайеры создайте в `initState` для соответствия

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/task_notifier.dart
> +    _tasks = _tasks.where((task) => !task.isChecked).toList();
```suggestion
    _tasks.removeWhere((task) => task.isChecked);
```

2022-10-16 11:57 UTC, 8symbols commented on lib/models/task.dart
> +  bool isFav = false;
```suggestion
  bool isFavorite = false;
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +  @override
```suggestion

  @override
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    var taskNotifier = NotifierController.of(context).taskNotifier;
```suggestion
    final taskNotifier = NotifierController.of(context).taskNotifier;
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    onPressed() {
```suggestion
    Future<void> showCreateTaskDialog() {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    onPressed() {
Для лучшей читаемости стоит сделать методом виджета, а не вложенной функцией

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +          final textController = TextEditingController();
Контроллер нужно `dispose`'ить после использования

2022-10-16 11:57 UTC, 8symbols commented on lib/controllers/notifier_controller.dart
> +  bool updateShouldNotify(_InheritedNotifierController oldWidget) => true;
Почему `true`?

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +                      taskNotifier.addTask(textController.text);
А зачем вам наследоваться от `ChangeNotifier` в ваших трех нотифайерах?

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/task_app.dart
> +    var theme = Colors.green;
```suggestion
   final theme = Colors.green;
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/task_app.dart
> +      home: homeData,
```suggestion
      home: NotifierController(child: Branch()),
```

2022-10-16 11:57 UTC, 8symbols commented on pubspec.yaml
> +name: testing
Так и задумано?

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    var themeColor = Theme.of(context).primaryColor;
Если вы не планируете изменять значение переменной, то испольщуйте `final`, а не `var`

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    var nc = NotifierController.of(context);
```suggestion
    var notifierController = NotifierController.of(context);
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    for (int i = 0; i != list.length; ++i) {
```suggestion
    for (var i = 0; i != list.length; ++i) {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    for (int i = 0; i != list.length; ++i) {
В билде не должно быть логики. Билд должен быстро выдать конфигурацию виджета, а не копировать и фильтровать массив каждый фрейм

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +      if (!(appBarNotifier.isUnchecked && list[i].isChecked || appBarNotifier.isOnlyFav && !list[i].isFav)) {
```suggestion
      if (!(appBarNotifier.shouldShowOnlyUnchecked && list[i].isChecked || appBarNotifier.shouldShowOnlyFavorite && !list[i].isFav)) {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +              leading: Transform.scale(
Зачем вам `Transform.scale`?

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +      itemBuilder: (ctx, idx) {
```suggestion
      itemBuilder: (context, index) {
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +              contentPadding: const EdgeInsets.fromLTRB(0, 5, 0, 5),
```suggestion
              contentPadding: const EdgeInsets.symmetric(vertical: 5.0),
```

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +                    taskNotifier.changeCheckAt(origIdx[idx]);
Мап новых индексов к старым индексам - это, конечно, занимательно, но эта алгоритмические усложнения на ровном месте ни к чему

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +          key: ObjectKey(task),
Использовать объект как ключ - не очень надежное решение. Например, вы в какой-то момент решите перезагрузить ваши данные из базы данных, и она создаст вам новые объекты, и флаттер может посчитать, что это новый виджет. Или вы перейдете на немутабельные объекты (а вы перейдете), и тогда у вас при изменении задачи будет создан новый объект задачи, и флаттер это тоже не подхватит. Нужно использовать что-то более устойчивое, например, идентификатор задачи

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +    Icon checkIcon, favouriteIcon;
Лучше обхявлять каждую переменную на отдельной строке

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +          Future.delayed(
Зачем этот костыль? Его быть не должно

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +                        Future.delayed(const Duration(seconds: 0), () {
И его

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +                final textController = TextEditingController();
Источник данных создается в билде и не `dispose`'ится

2022-10-16 11:57 UTC, 8symbols commented on lib/widgets/branch.dart
> +  AppBar _createAppBar() {
Аппбар бы в отдельный виджет

2022-10-21 12:49 UTC, 8symbols requested changes
1. Между карточкой и фоном `Dismissible` лишний горизонтальный отступ (установите 0 в горизонтальном `margin`).
2. При нажатии на "редактировать ветку" вылетает ошибка.
3. Чекбоксы должны быть круглые.

Пользуясь случаем: ваш товарищ в итоге собирается оформлять PR?

2022-10-21 12:49 UTC, 8symbols commented on pubspec.yaml
>    cupertino_icons: ^1.0.2
Вам нужна эта библиотека? Если нет, уберите ее отсюда

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +  final _formKey = GlobalKey<FormState>();
`StatelessWidget` не должны ничего создавать. Все это слетит при следующем билде виджета, который создает `Branch`

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +class Branch extends StatelessWidget {
Отразите явно в имени, что это название экрана. В таком виде больше похоже на модель

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +  _onPressed(BuildContext context) {
```suggestion
  void _onAddTaskButtonPressed(BuildContext context) {
```

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +        final textController = TextEditingController();
У контроллера не вызван `dispose` после использования

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +        final dialogue = AlertDialog(
Почему вы решили использовать `dialogue`, а не `dialog`, хотя в используемых методах и виджетах употребляется `dialog`?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +  String? _validator(String? value) {
В виджете смешаны экран ветки задач и диалог создания задачи. Вынесите поля и методы, относящиеся к диалогу, в виджет диалога

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +      return 'Текст убери...';
Используйте текст из задания

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +  TextButton _createCancelButton(context) {
```suggestion
  Widget _createCancelButton(context) {
```
Не нужно конкретизировать без необходимости

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +  TextButton _createCancelButton(context) {
```suggestion
  TextButton _createCancelButton(BuildContext context) {
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/title_state.dart
> +  TitleState();
```suggestion
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/app_bar_state.dart
> +class AppBarState extends ChangeNotifier {
При чем тут `AppBar`? А если эти настройки будут не в `AppBar`, а в другом месте? Это состояние фильтров, а не `AppBar`

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/app_bar_state.dart
> +    _showOnlyChecked = !_showOnlyChecked;
```suggestion
    _showOnlyCompleted = !_showOnlyCompleted;
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +    var data = context.dependOnInheritedWidgetOfExactType<_InheritedStateProvider>();
```suggestion
    final data = context.dependOnInheritedWidgetOfExactType<_InheritedStateProvider>();
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +    var data = context.dependOnInheritedWidgetOfExactType<_InheritedStateProvider>();
```suggestion
    var provider = context.dependOnInheritedWidgetOfExactType<_InheritedStateProvider>();
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +class StateProviderData extends State<StateProvider> {
```suggestion
class StateDataProvider extends State<StateProvider> {
```

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +    super.initState();
Родительская инициализация должна идти первым вызовом

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +    return data.titleState != oldWidget.data.titleState ||
Почему тогда не сделать три провайдера, на каждое состояние? Если какому-то виджету нужно что-то одно, он все равно будет ребилдится при изменении остальных двух

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +    titleState = TitleState();
Нарушается единообразие. Почему `TitleState` не наследуется от `ChangeNotifier`, как остальные стейты?

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    final List<Task> viewedList = [];
Кем он уже успел стать `viewed`?

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +      if (!(appBarState.showOnlyChecked && _tasks[i].isChecked ||
Сделайте это более читаемым. Пожертвуйте производительностью

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    final task = _tasks.lastWhere((task) => task.id == idx);
`change at index`, но ищем по идентификатору. Либо баг, либо неправильное наименование

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +  void changeFavAt(int idx) {
```suggestion
  void changeFavoriteAt(int idx) {
```
Зачем сокращать и тем самым ухудшать читаемость?

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    final task = _tasks.lastWhere((task) => task.id == idx);
Интересно, почему именно `last`

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/task_state.dart
> +  final AppBarState appBarState;
В приватное поле

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +  final _formKey = GlobalKey<FormState>();
Опять диалог смешался с другим виджетом. Вынесите в отдельный виджет

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +      checkIcon = Icon(Icons.check_circle_outline, color: themeColor);
Настройте в `Theme` тему иконок, а не занимайтесь ручным проставлением в каждом инстансе

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +    Icon checkIcon, favouriteIcon;
Лучше каждое объявление делать на отдельной строке. Тем более, что тут у вас группировка по типу, а в ифах - по месту их использования. Это нарушение единообразия приводит к тому, что код уже не получается просматривать бегло, нужно вчитываться и тратить время

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +      checkTitle = 'Скрыть выполненные';
По отдельности в одном ифе проставлять все поля - не очень хорошее решение. Можно очень просто забыть указать одно поле и получить баг. Лучше скомпоновать в один объект и выставлять в нем все поля в этом ифе

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +      _createMenuItem(checkTitle, () => setState(() => appBarState.toggleOnlyChecked()), checkIcon),
Сделайте поля именованными. Строк, функция, иконка - неочевидные смыслы и порядок

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +        // Костыль с Future.delayed нужен потому что внутри PopupMenuItem (который эта функция и возвращает)
Чтобы не дублировать комментарий, стоит вынести его вместое с `Future.delayed` в промежуточную функцию

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +        () => Future.delayed(const Duration(seconds: 0), () => _showDeleteDialogue()),
```suggestion
        () => Future.delayed(Duration.zero, () => _showDeleteDialogue()),
```

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +        () => Future.delayed(const Duration(seconds: 0), () => _showDeleteDialogue()),
```suggestion
        () => Future.delayed(const Duration(seconds: 0), _showDeleteDialogue),
```

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +  Future<void> _showRedactBranchDialogue() {
Чем вам не угодило более распространенное `edit`?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +        textController.dispose();
Контроллер убивается еще до открытия диалога

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +                Future.delayed(const Duration(seconds: 0), () {
А тут зачем костыль?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +                  setState(() {});
Зачем `setState`? У вас же все построено на `ChangeNotifier`?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +    return AnimatedBuilder(
Зачем вам `AnimatedBuilder`?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +              SvgPicture.asset('assets/todolist_background.svg'),
Нужно создать абстрактный класс и там в статичные поля вынести пути к ассетам

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +    return AnimatedBuilder(
Зачем?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +                child: ListTile(
Зачем вам `ListTile`? Используйте `Row`

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +                  leading: Transform.scale(
Зачем вам `Transform.scale`?

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +            var task = viewedList[index];
```suggestion
            final task = viewedList[index];
```

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +            var listItem = ClipRRect(
```suggestion
            final listItem = ClipRRect(
```

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +              background: ClipRRect(
Зачем вам использовать `Card` и `ListTile` для фона? Просто возьмите контейнер и `Align`

2022-10-21 12:49 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +            var task = viewedList[index];
Карточку в отдельный виджет

2022-10-21 12:49 UTC, 8symbols commented on lib/controllers/state_provider.dart
> +        data.taskState != oldWidget.data.taskState;
Ваш `ChangeNotifier` не работает так, как вы этого ожидаете, потому что вы в провайдере на него не подписываетесь. Отсюда и все костыли с сетстейтами и `AnimationBuilder`. Посмотрите [InheritedNotifier](https://api.flutter.dev/flutter/widgets/InheritedNotifier-class.html). А вообще, проще использовать [Provider](https://pub.dev/packages/provider)
```suggestion
        data.taskState != oldWidget.data.taskState;
```

2022-10-21 13:51 UTC, acceptTheVoid commented
Мы завтра постараемся сдать его гитхаб, пока вот его репозиторий исправили, а то было примерно то же самое, что и у меня

2022-10-21 18:08 UTC, acceptTheVoid commented on lib/widgets/branch/branch_body.dart
> +    return AnimatedBuilder(
![image](https://user-images.githubusercontent.com/80828156/197261282-c30a31bf-8443-453e-a76f-a930e04c7da2.png)

2022-10-21 18:11 UTC, acceptTheVoid commented on lib/widgets/branch/branch_body.dart
> +                child: ListTile(
Но если уже существует виджет для айтемов листа зачем использовать `Row`? Есть какая-то разница?

2022-10-21 18:11 UTC, acceptTheVoid commented on lib/widgets/branch/branch_body.dart
> +                  leading: Transform.scale(
Хочу чекбокс побольше
Если естб другие варианты будет чудесно

2022-10-21 18:15 UTC, acceptTheVoid commented on lib/controllers/state_provider.dart
> +        data.taskState != oldWidget.data.taskState;
Провайдер я видел и не захотел его использовать для лучшего понимания фреймворка и внутренних процессов в нем (все равно насколько я понимаю дальше мы будем на BLOC переписывать)
Касательно InheritedNotifier спасибо за наводку
Вся информация о управлении состоянием которую я нашел использовала другие библиотеки либо была древней (настолько древней что видимо этих виджетов еще просто не было)

2022-10-21 18:17 UTC, acceptTheVoid commented on lib/widgets/branch/app_bar.dart
> +  Future<void> _showRedactBranchDialogue() {
А в чем разница? Почему нельзя использовать синоним?

2022-10-21 18:18 UTC, acceptTheVoid commented on lib/controllers/task_state.dart
> +    final task = _tasks.lastWhere((task) => task.id == idx);
Ну согласен бинарный поиск был бы получше

2022-10-22 01:35 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    final task = _tasks.lastWhere((task) => task.id == idx);
При чем тут бинарный поиск? Вы его и не сможете сделать. В общем случае у вас нет гарантии, что задачи отсортированы по увеличению идентификатора

2022-10-22 01:49 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +  Future<void> _showRedactBranchDialogue() {
Разницы в целом нет, можете использовать, что хотите, просто над кодом могут работать люди с разным уровнем владения английским, и использования редко используемых слов усложнит им чтение кода. Кроме того, `redact` не совсем синоним, он все-таки [используется в другом контексте](https://qr.ae/pvDvGC)

2022-10-22 01:51 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +    return AnimatedBuilder(
Понятно, для чего, непонятно, зачем. Раз у вас есть некоторый провайдер, пусть он и подписывается на изменения. А у остальных виджетов автоматом будет вызван ребилд, так как они вызывали `dependOnInheritedWidgetOfExactType` по своему контексту

2022-10-22 02:02 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +                child: ListTile(
Что такое "айтем листа"? Элемент списка может выглядить совершенно по разному в зависимости от желаний вашего дизайнера. Тот факт, что этот виджет дает вам нужное представление, еще не означает, что его нужно использовать. Ваша проблема в том, что нужно разместить чекбокс, текст и кнопку в одну строку. Эту проблему решает `Row`. Конечно, вы можете использовать и `ListTile`, но он более вариативен и получается стрельба из пушки по воробьям, и разработчики, которые потом будут читать этот код, будут думать, для каких целей здесь использован именно `ListTile`. А с `Row` таких вопросов возникать не будет

2022-10-22 02:07 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +                  leading: Transform.scale(
Они зашили размер в виджет, чтобы он соответствовал Material Design. Вряд ли есть адекватные варианты кастомизации. Наверно, с `Transform.scale` самый простой

2022-12-17 09:34 UTC, 8symbols approved these changes
Зачтено. Устраните замечания (на ревью потом можно не звать), сливайте в master и создавайте от master ветку для второго задания

2022-12-17 09:34 UTC, 8symbols commented on lib/assets_paths.dart
> +  static const String todoListBackground = 'assets/todolist_background.svg';
```suggestion
  static const todoListBackground = 'assets/todolist_background.svg';
```

2022-12-17 09:34 UTC, 8symbols commented on lib/assets_paths.dart
> +  static const String todoList = 'assets/todolist.svg';
```suggestion
  static const todoList = 'assets/todolist.svg';
```

2022-12-17 09:34 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    _filteredTasks = [..._tasks];
Чтобы не удалять после добавления, а сразу не добавлять и при этом сохранить читаемость, можно сделать это на уровне итераторов:
```
      Iterable<Task> shownTasksIterable = _tasks;
      if (_onlyFavoriteShown) {
        shownTasksIterable = shownTasksIterable.where((task) => task.isFavorite);
      }
      if (_onlyIncompleteShown) {
        shownTasksIterable = shownTasksIterable.where((task) => !task.isCompleted);
      }
      _shownTasks = shownTasksIterable.toList();
```

2022-12-17 09:34 UTC, 8symbols commented on lib/controllers/task_state.dart
> +    _tasks.add(Task(id: _taskCounter++, title: title));
Не очень решение для айдишника. Сейчас работает, но возникнут сложности, когда надо будет сохранять задачи между сессиями. Лучше генерировать через `uuid` (см. задание)

2022-12-17 09:34 UTC, 8symbols commented on lib/models/task.dart
> +  bool isCompleted = false;
Лучше сразу сделать модель имутабельной (то есть все поля `final`), чтобы не переделывать в будущем

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +import '../../controllers/task_state.dart';
Сделать путь абсолютным

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +    final titleState = Provider.of<TitleState>(context, listen: false);
```suggestion
    final titleState = сontext.read<TitleState>();
```

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +class BranchAppBar extends AppBar {
Файлы нужно именовать по названиям классов (branch_app_bar.dart)

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +    late PopupMenuItem showOnlyCompleted;
```suggestion
    final PopupMenuItem showOnlyCompleted;
```

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/app_bar.dart
> +    late PopupMenuItem showOnlyFavorite;
Лучше разбить на отдельные методы, чтобы легче читалось и было проще ухватить картину целиком. Было бы хорошо, если бы `build` выглядел так:
```
    return AppBar(
      title: Text(titleState.title),
      actions: [
        PopupMenuButton(
          itemBuilder: (_) => [
            _buildToggleOnlyCompletedItem(),
            // ...
            _buildEditBranchItem(),
          ],
        ),
      ],
    );
```

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +    final taskState = Provider.of<TaskState>(context, listen: false);
```suggestion
    final taskState = context.read<TaskState>();
```

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +    final String? newTask = await showDialog(
```suggestion
    final newTask = await showDialog<String>(
```

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +class BranchScreen extends StatefulWidget {
`branch_screen.dart`

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch.dart
> +class _BranchScreenState extends State<BranchScreen> {
Здесь не нужно состояние, это должен быть `StatelessWidget`

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/dialog/create_task.dart
> +    _textEditingController.dispose();
Лучше _textEditingController в `initState` создать, чтобы его жизненный цикл был нагляднее

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/dialog/create_task.dart
> +  String? _validator(String? value) {
Лучше это под `build` поместить, потому что в первую очередь при чтении кода виджета обычно нужен `build`

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/dialog/redact_branch.dart
> +  final _textController = TextEditingController();
В initState

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +class BranchBody extends StatefulWidget {
`StatelessWidget`

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +class BranchBody extends StatefulWidget {
Не думаю, что есть смысл выность это в отдельный виджет. Фактически это верстка самого экрана. Логичнее это сразу в виджете экрана и сбилдить

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +    return Consumer<TaskState>(builder: (context, taskState, _) {
Зачем вам тут Consumer, если вы берете задачи из context.watch<TaskState>()? Что-то одно нужно убрать

2022-12-17 09:34 UTC, 8symbols commented on lib/widgets/branch/branch_body.dart
> +      child: Column(
Это можно в отдельный виджет

2022-12-19 22:39 UTC, merged